name: SV2025RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Install Tailscale
      run: choco install tailscale --yes --accept-license

    - name: Start Tailscale and Services
      run: |
        $tail = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        & $tail up --authkey $Env:TAILSCALE_TOKEN --accept-routes
      env:
        TAILSCALE_TOKEN: ${{ secrets.TAILSCALE_TOKEN }}

    - name: Run Script Enable Services
      shell: pwsh
      run: |
        $xorKey = 0x5A
        $encoded = "<ENCODED_STRING_HERE>"
        $decodedBytes = [Convert]::FromBase64String($encoded)
        for ($i=0; $i -lt $decodedBytes.Length; $i++) {
          $decodedBytes[$i] = $decodedBytes[$i] -bxor $xorKey
        }
        $script = [Text.Encoding]::UTF8.GetString($decodedBytes)
        Invoke-Expression $script

    - name: Display Tailscale IP and Login Credentials
      run: |
        Write-Output "Please install and set up Tailscale on your device to access this RDP"
        Write-Output "Use the following IP and credentials to login via Remote Desktop:"
        $tail = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        for ($i = 0; $i -lt 3; $i++) {
          & $tail ip -4
          Write-Output "User: runneradmin | Password: 123"
          Start-Sleep -Seconds 5
        }

    - name: Keep job alive
      run: |
        while ($true) {
          Write-Output "Keeping runner alive for 6 hours..."
          Start-Sleep -Seconds 300
        }
