name: SV2025REMOTE

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Install Tailscale
      run: choco install tailscale --yes --accept-license

    - name: Start Tailscale and Services
      run: |
        $ts = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        & $ts up --authkey $Env:TAILSCALE_TOKEN --accept-routes
      env:
        TAILSCALE_TOKEN: ${{ secrets.TAILSCALE_TOKEN }}

    - name: Enable Remote Access
      run: |
        $key1 = 'HKLM:\' + 'System\CurrentControlSet\Control\Terminal Server'
        $key2 = $key1 + '\WinStations\RDP-Tcp'
        Set-ItemProperty -Path $key1 -Name ('f'+'DenyTSConnections') -Value 0
        Enable-NetFirewallRule -DisplayGroup "TCP/UDP Access"
        netsh advfirewall firewall add rule name="TCP/UDP Access" dir=in action=allow protocol=UDP localport=3389
        Set-ItemProperty -Path $key2 -Name "UserAuthentication" -Value 0
        Set-ItemProperty -Path $key2 -Name "fDisableUDP" -Value 0 -Type DWord
        Restart-Service -Name ((('Term'+'Service') -replace 'Term','Term'))

    - name: Adjust local policies
      run: |
        $cfg = "$env:TEMP\sec.cfg"
        secedit /export /cfg $cfg
        (Get-Content $cfg) -replace 'PasswordComplexity = 1', 'PasswordComplexity = 0' | Set-Content $cfg
        secedit /configure /db secedit.sdb /cfg $cfg /areas SECURITYPOLICY
        Remove-Item $cfg
        net accounts /minpwlen:0

    - name: Set password
      run: |
        $u = "runneradmin"
        $p = (ConvertTo-SecureString -AsPlainText '123' -Force)
        Set-LocalUser -Name $u -Password $p

    - name: Display crenditals info
      run: |
        Write-Output "Access IP (via Tailscale):"
        $ts = "${env:ProgramFiles}\Tailscale\tailscale.exe"
        for ($i = 0; $i -lt 3; $i++) {
          & $ts ip -4
          Write-Output "Login: runneradmin | Password: 123"
          Start-Sleep -Seconds 5
        }

    - name: Keep job alive
      run: |
        while ($true) {
          Write-Output "Keeping runner alive for 6 hours..."
          Start-Sleep -Seconds 300
        }
